dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 19]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [14, 33]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [28, 47]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [42, 61]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [56, 80]
    model: cognitivecomputations/dolphin-2.2-70b