dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 23]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [18, 41]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [36, 59]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [54, 80]
    model: cognitivecomputations/dolphin-2.2-70b