dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 1]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [1, 2]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [2, 3]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [3, 4]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [4, 5]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [5, 6]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [6, 7]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [7, 8]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [8, 9]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [9, 10]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [10, 11]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [11, 12]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [12, 13]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [13, 14]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [14, 15]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [15, 16]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [16, 17]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [17, 18]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [18, 19]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [19, 20]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [20, 21]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [21, 22]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [22, 23]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [23, 24]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [24, 25]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [25, 26]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [26, 27]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [27, 28]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [28, 29]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [29, 30]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [30, 31]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [31, 32]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [32, 33]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [33, 34]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [34, 35]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [35, 36]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [36, 37]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [37, 38]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [38, 39]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [39, 40]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [40, 41]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [41, 42]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [42, 43]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [43, 44]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [44, 45]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [45, 46]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [46, 47]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [47, 48]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [48, 49]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [49, 50]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [50, 51]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [51, 52]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [52, 53]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [53, 54]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [54, 55]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [55, 56]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [56, 57]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [57, 58]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [58, 59]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [59, 60]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [60, 61]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [61, 62]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [62, 63]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [63, 64]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [64, 65]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [65, 66]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [66, 67]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [67, 68]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [68, 69]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [69, 70]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [70, 71]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [71, 72]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [72, 73]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [73, 74]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [74, 75]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [75, 76]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [76, 77]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [77, 78]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [78, 80]
    model: cognitivecomputations/dolphin-2.2-70b