dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 22]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [12, 34]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [24, 46]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [36, 58]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [48, 70]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [60, 80]
    model: cognitivecomputations/dolphin-2.2-70b