dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 29]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [23, 52]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [46, 80]
    model: cognitivecomputations/dolphin-2.2-70b