dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 20]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [11, 31]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [22, 42]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [33, 53]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [44, 64]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [55, 75]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [66, 80]
    model: cognitivecomputations/dolphin-2.2-70b