dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 14]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [9, 23]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [18, 32]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [27, 41]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [36, 50]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [45, 59]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [54, 68]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [63, 80]
    model: cognitivecomputations/dolphin-2.2-70b