dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 27]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [22, 49]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [44, 80]
    model: cognitivecomputations/dolphin-2.2-70b