dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 7]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [5, 12]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [10, 17]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [15, 22]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [20, 27]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [25, 32]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [30, 37]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [35, 42]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [40, 47]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [45, 52]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [50, 57]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [55, 62]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [60, 67]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [65, 72]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [70, 80]
    model: cognitivecomputations/dolphin-2.2-70b