dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 22]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [20, 42]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [40, 80]
    model: cognitivecomputations/dolphin-2.2-70b