dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 13]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [10, 23]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [20, 33]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [30, 43]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [40, 53]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [50, 63]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [60, 80]
    model: cognitivecomputations/dolphin-2.2-70b