dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 8]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [7, 15]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [14, 22]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [21, 29]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [28, 36]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [35, 43]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [42, 50]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [49, 57]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [56, 64]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [63, 71]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [70, 80]
    model: cognitivecomputations/dolphin-2.2-70b