dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 6]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [3, 9]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [6, 12]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [9, 15]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [12, 18]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [15, 21]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [18, 24]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [21, 27]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [24, 30]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [27, 33]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [30, 36]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [33, 39]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [36, 42]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [39, 45]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [42, 48]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [45, 51]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [48, 54]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [51, 57]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [54, 60]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [57, 63]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [60, 66]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [63, 69]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [66, 72]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [69, 75]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [72, 78]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [75, 80]
    model: cognitivecomputations/dolphin-2.2-70b