dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 25]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [15, 40]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [30, 55]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [45, 70]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [60, 80]
    model: cognitivecomputations/dolphin-2.2-70b