dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 27]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [17, 44]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [34, 61]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [51, 80]
    model: cognitivecomputations/dolphin-2.2-70b