dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 17]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [10, 27]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [20, 37]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [30, 47]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [40, 57]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [50, 67]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [60, 80]
    model: cognitivecomputations/dolphin-2.2-70b