dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 14]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [13, 27]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [26, 40]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [39, 53]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [52, 66]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [65, 80]
    model: cognitivecomputations/dolphin-2.2-70b