dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 9]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [6, 15]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [12, 21]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [18, 27]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [24, 33]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [30, 39]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [36, 45]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [42, 51]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [48, 57]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [54, 63]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [60, 69]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [66, 75]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [72, 80]
    model: cognitivecomputations/dolphin-2.2-70b