dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 16]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [8, 24]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [16, 32]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [24, 40]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [32, 48]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [40, 56]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [48, 64]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [56, 72]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [64, 80]
    model: cognitivecomputations/dolphin-2.2-70b