dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 21]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [14, 35]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [28, 49]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [42, 63]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [56, 80]
    model: cognitivecomputations/dolphin-2.2-70b