dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 4]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [2, 6]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [4, 8]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [6, 10]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [8, 12]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [10, 14]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [12, 16]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [14, 18]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [16, 20]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [18, 22]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [20, 24]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [22, 26]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [24, 28]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [26, 30]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [28, 32]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [30, 34]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [32, 36]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [34, 38]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [36, 40]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [38, 42]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [40, 44]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [42, 46]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [44, 48]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [46, 50]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [48, 52]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [50, 54]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [52, 56]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [54, 58]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [56, 60]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [58, 62]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [60, 64]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [62, 66]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [64, 68]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [66, 70]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [68, 72]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [70, 74]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [72, 76]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [74, 78]
    model: cognitivecomputations/dolphin-2.2-70b
- sources:
  - layer_range: [76, 80]
    model: cognitivecomputations/dolphin-2.2-70b